"""Markdown / CSV / webhook output."""

from __future__ import annotations

import csv
import io
import json
from typing import Iterable, List, Mapping, Optional

import requests


def _pct(x: float) -> str:
    return f"{x*100:.0f} %"


def markdown_report(summary: dict, run_id: int, brands: List[str], providers: List[str], prompts_n: int) -> str:
    lines: List[str] = []
    lines.append(f"# AI visibility report — run #{run_id}")
    lines.append("")
    lines.append(f"{prompts_n} prompts × {len(providers)} engines ({', '.join(providers)}) · brands: {', '.join(brands)}")
    lines.append("")
    lines.append("## Overall")
    lines.append("")
    lines.append("| Brand | Mention rate | Citation rate | Share of voice | Δ SoV vs previous |")
    lines.append("|---|---:|---:|---:|---:|")
    delta = summary.get("delta", {})
    for b in brands:
        s = summary["overall"].get(b)
        if not s:
            continue
        d = delta.get(b, {}).get("share_of_voice")
        d_txt = "—" if d is None else (f"+{d*100:.0f} pt" if d >= 0 else f"{d*100:.0f} pt")
        lines.append(f"| {b} | {_pct(s['mention_rate'])} | {_pct(s['citation_rate'])} | {_pct(s['share_of_voice'])} | {d_txt} |")
    lines.append("")
    lines.append("## By engine")
    lines.append("")
    for p, table in summary["by_provider"].items():
        lines.append(f"**{p}**")
        lines.append("")
        lines.append("| Brand | Mentions | Citations | SoV |")
        lines.append("|---|---:|---:|---:|")
        for b in brands:
            s = table.get(b)
            if s:
                lines.append(f"| {b} | {s['mentions']}/{s['prompts']} | {s['citations']}/{s['prompts']} | {_pct(s['share_of_voice'])} |")
        lines.append("")
    gaps = summary.get("gaps", [])
    lines.append(f"## Gaps — competitor cited, you are not ({len(gaps)})")
    lines.append("")
    if not gaps:
        lines.append("None. 🎉")
    for g in gaps[:50]:
        lines.append(f"- **{g['provider']}** · \"{g['prompt']}\" → {', '.join(g['competitors_mentioned'])}")
    lines.append("")
    lines.append("_Generated by ai-visibility-tracker._")
    return "\n".join(lines)


def csv_rows(rows: Iterable[Mapping]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["provider", "prompt", "brand", "mentioned", "mention_count", "cited", "cited_urls", "first_position"])
    for r in rows:
        w.writerow([r["provider"], r["prompt"], r["brand"], r["mentioned"], r["mention_count"], r["cited"], r["cited_urls"], r["first_position"]])
    return buf.getvalue()


def post_webhook(url: str, payload: dict, timeout: int = 30) -> int:
    """Send the summary to n8n / Make / Zapier. Returns HTTP status."""
    resp = requests.post(url, data=json.dumps(payload, default=str), headers={"Content-Type": "application/json"}, timeout=timeout)
    return resp.status_code


def logs_markdown(report: List[dict], recs: List[str]) -> str:
    lines = ["# AI crawler report", ""]
    lines.append("| Bot | Vendor | Hits | Blocked | Active days | Top path |")
    lines.append("|---|---|---:|---:|---:|---|")
    for r in report:
        top = r["top_paths"][0][0] if r["top_paths"] else "—"
        lines.append(f"| {r['bot']} | {r['vendor']} | {r['hits']} | {_pct(r['blocked_rate'])} | {r['active_days']} | `{top}` |")
    lines.append("")
    lines.append("## Recommendations")
    lines.append("")
    for rec in recs:
        lines.append(f"- {rec}")
    return "\n".join(lines)
